Restore a patch I mistakenly removed during code style clean up
First I thought the patch was unnecessary because there is no update
services provided for FreeBSD. However, without the change code-oss
does not start with the following error:

Error: [invokeFunction] unknown service 'updateService'

Reported at: https://github.com/tagattie/FreeBSD-VSCode/issues/44#issuecomment-2994754085